# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 李康炜的技术博客
email: 262708239@qq.com
description:  淘生词插件开发者。淘生词: http://readdoc.net.

baseurl: "http://likangwei.com/blog" # the subpath of your site, e.g. /blog
url: "http://likangwei.com" # the base hostname & protocol for your site
twitter_username: 
github_username:  likangwei

# Build settings
markdown: kramdown
